# demo-cards.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: team5-eureka-client-card
  namespace: under76-test
spec:
  replicas: 3
  selector:
    matchLabels:
      app: team5-eureka-client-card
  template:
    metadata:
      labels:
        app: team5-eureka-client-card
    spec:
      containers:
      - name: team5-eureka-client-card
        image: k8s-vga-worker1:5000/img-team5-eureka-client-card:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8070
---
apiVersion: v1
kind: Service
metadata:
  name: team5-eureka-client-card
  namespace: under76-test
spec:
  selector:
    app: team5-eureka-client-card
  ports:
    - protocol: TCP
      port: 8070
      targetPort: 8070
      nodePort: 30297
  type: NodePort
